/**
 * Generates src/styles/tokens.css from src/lib/theme.ts.
 *
 * Run with:  bun run scripts/gen-tokens.mjs
 *
 * Emits all 14 palettes as CSS custom properties. Bare :root is the design
 * default (signature + dark) so first paint is correct with zero JS. The
 * [data-theme][data-mode] selectors let the FOUC script and theme switcher
 * swap palettes by toggling two attributes on <html>.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { THEMES, PALETTES, paletteVars, deepShade } from '../src/lib/theme.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const out = join(__dirname, '..', 'src', 'styles', 'tokens.css');

const MODES = ['dark', 'light'];

function block(selector, vars) {
  const lines = Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`);
  return `${selector} {\n${lines.join('\n')}\n}`;
}

// Brand mark colours are fixed per theme family and DO NOT change with the
// light/dark mode, so the logo stays stable when the user toggles the mode
// (the launcher icon is a brand mark, not themed UI). They use each family's
// dark accent. Switching the accent family still recolours the logo.
const sigAcc = PALETTES.signature.dark.accent;
const rootVars = {
  ...paletteVars(PALETTES.signature.dark, 'dark'),
  '--k-brand-circle': sigAcc,
  '--k-brand-tile': deepShade(sigAcc),
};

const parts = [
  '/* AUTO-GENERATED by scripts/gen-tokens.mjs. Do not edit by hand. */',
  '/* Source of truth: src/lib/theme.ts. Regenerate: bun run gen:tokens */',
  '',
  '/* Default palette: Kuber Signature, Obsidian (dark). */',
  block(':root', rootVars),
  '',
  '/* Brand mark colours: fixed per family, mode-independent. */',
  ...THEMES.map((t) => {
    const acc = PALETTES[t.id].dark.accent;
    return `:root[data-theme="${t.id}"] { --k-brand-circle: ${acc}; --k-brand-tile: ${deepShade(acc)}; }`;
  }),
  '',
];

for (const t of THEMES) {
  for (const mode of MODES) {
    const sel = `:root[data-theme="${t.id}"][data-mode="${mode}"]`;
    parts.push(block(sel, paletteVars(PALETTES[t.id][mode], mode)));
    parts.push('');
  }
}

// Active-state selectors for the theme switcher rows/chips, keyed off the html
// attribute so the selected family highlights with zero JS and no flash.
parts.push('/* Theme switcher active states (family selected on <html>). */');
for (const t of THEMES) {
  parts.push(
    `:root[data-theme="${t.id}"] [data-set-variant="${t.id}"] { background: var(--k-accent-subtle); border-color: var(--k-accent-ring) !important; }`,
  );
}
parts.push('');
parts.push('/* Mode toggle active states. */');
parts.push(
  ':root[data-mode="light"] [data-set-mode="light"], :root[data-mode="dark"] [data-set-mode="dark"] {',
);
parts.push('  color: var(--k-accent-text);');
parts.push('  background: var(--k-accent-subtle);');
parts.push('  border-color: var(--k-accent-ring) !important;');
parts.push('}');
parts.push('');

writeFileSync(out, parts.join('\n'), 'utf8');
console.log(`Wrote ${out} (${THEMES.length * MODES.length} palettes).`);
